version: '2'

services:
    
    #DATABASE
    db-flask:
        image: 'postgres'
        container_name: db-flask
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=siscov
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_DB=postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "siscov@temp.br"
            PGADMIN_DEFAULT_PASSWORD: "siscov"
        ports:
        - "3001:80"
        depends_on:
        - db-flask

volumes:
    postgres_data:
