version: '2'

services:

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    #DATABASE
    db:
        image: 'postgres'
        container_name: db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=siscov
        volumes:
            - ./volume:/var/lib/postgresql/data 
    
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "siscov@temp.br"
            PGADMIN_DEFAULT_PASSWORD: "siscov"
        ports:
            - "3001:80"
        depends_on:
            - db
